#version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper
    container_name: zookeeper
    ports: ["2181:2181"]
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: [flinknet]        # ✨ explicit network

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka
    container_name: kafka
    depends_on: [zookeeper]
    ports:
      - "9092:9092"             # host → Kafka
      - "9093:9093"             # internal listener
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:9092"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1   # ✨ was empty
    networks: [flinknet]        # ✨ explicit network

  jobmanager:
    image: flink:1.20.1-scala_2.12 # full JDK build
    container_name: jobmanager
    ports: ["8081:8081"]
    command: jobmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
    volumes:
      - ./target:/jobdir        # ✨ expose fat-JARs
    networks: [flinknet]

  taskmanager:
    image: flink:1.20.1-scala_2.12
    container_name: taskmanager
    depends_on: [jobmanager]
    command: taskmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
    volumes:
      - ./target:/jobdir        # ✨ expose fat-JARs
    networks: [flinknet]

networks:
  flinknet: {}                  # ✨ declare once
